### ISSUE TITLE
Fails when using jena core 3.14

### ISSUE THREAD

**Issue by MarcAgate** [BuddhistDigitalResourceCenter/jena-stable-turtle#2]
We have the following exception in ldspdi when upgrading  to jena 3.14 and using sttl writer
This should be upgraded to jene-arq 3.14. (currently 3.11)

```
java.lang.NoSuchMethodError: org.apache.jena.riot.system.RiotLib.writeBase(Lorg/apache/jena/atlas/io/IndentedWriter;Ljava/lang/String;)V
	at io.bdrc.jena.sttl.TurtleShell.writeBase(TurtleShell.java:106)
	at io.bdrc.jena.sttl.TurtleShell.write(TurtleShell.java:146)
	at io.bdrc.jena.sttl.STTLWriter.output(STTLWriter.java:71)
```

**Comment by MarcAgate** [comment]
Fixed as of commit ed5d7d6
The only required change can be seen here:
https://github.com/buda-base/jena-stable-turtle/commit/ed5d7d6a25b1ea7099b3c053c69fadd3a4560ba3#diff-1182dac3348b866c532fd190edd2a615R119
